language: python

python:
  - "3.4.5"
  - "3.5"

before_script: 
  - npm install -g bower
  - cd digital_milliet && bower install -f && cd ..
services:
  - mongodb

install:
  - python setup.py install
  - pip install coveralls

# command to run tests
script:
  - coverage run --source=digital_milliet setup.py test

matrix:

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi
