version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: scripts/wait-for-mongo.sh python3 run.py
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
