version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: scripts/wait-for-mongo.sh python3 run.py --env
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - DIGMILL_MONGO_HOST=mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
